### PR TITLE
Doxygen docs

### PR DESCRIPTION
**Pull request by juanjux**
- Added doc/Doxyfile
- Modified instructions in doc/README.md to show how to (re)generate doxygen stuff.
- Linked from Sphinx' index.html to Doxygen docs (if generated).

TODO: modify the Makefile to generate both Doxygen and Sphinx docs when making "make html" to avoid one manual step.

### CODE REVIEW

**Comment by mcuadros** [comment]
why? all this things are handled by `docserv` and the platform team.
/cc @erizocosmico

**Comment by erizocosmico** [comment]
You don't need to add a Doxyfile or anything like that. You have the examples of how to document the projects here (still things missing): https://github.com/src-d/ci/tree/master/examples/docs/cpp

**Comment by vmarkovtsev** [comment]
I need to add Doxyfile! Of course I do. Every C++ project is unique and requires additional configuration. There is no "one fits all".

**Comment by erizocosmico** [comment]
What configuration would you need in the `Doxyfile`? This already scans recursively for code and scans comments to generate the docs.

**Comment by vmarkovtsev** [comment]
Hoho, welcome to the world of C++. Let me show you examples at the office.

**Pull request merged**
